In [1]:
import tensorflow as tf

x = tf.Variable(2, name='x', dtype=tf.float32)
log_x = tf.log(x)
log_x_squared = tf.square(log_x)

optimizer = tf.train.GradientDescentOptimizer(0.5)
train = optimizer.minimize(log_x_squared)

init = tf.initialize_all_variables()

def optimize():
  with tf.Session() as session:
    session.run(init)
    print("starting at", "x:", session.run(x), "log(x)^2:", session.run(log_x_squared))
    for step in range(10):  
      session.run(train)
      print("step", step, "x:", session.run(x), "log(x)^2:", session.run(log_x_squared))
        

optimize()

/home/danielchan/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


Instructions for updating:
Use `tf.global_variables_initializer` instead.
starting at x: 2.0 log(x)^2: 0.480453
step 0 x: 1.6534264 log(x)^2: 0.25285786
step 1 x: 1.3493005 log(x)^2: 0.08975195
step 2 x: 1.1272697 log(x)^2: 0.014351694
step 3 x: 1.0209966 log(x)^2: 0.0004317743
step 4 x: 1.0006447 log(x)^2: 4.1534943e-07
step 5 x: 1.0000006 log(x)^2: 3.5527118e-13
step 6 x: 1.0 log(x)^2: 0.0
step 7 x: 1.0 log(x)^2: 0.0
step 8 x: 1.0 log(x)^2: 0.0
step 9 x: 1.0 log(x)^2: 0.0


In [23]:
import tensorflow as tf

# initialize arrays
x1_data = tf.Variable(initial_value=tf.random_uniform([1], -3, 3),name='x1')
x2_data = tf.Variable(initial_value=tf.random_uniform([1], -3, 3), name='x2')

# The Rosenbrock problem is defined as y = (1 - x1)^2 + 100 * (x2 - x1^2)^2, 
# giving the optimal solution on x1 = x2 = 1

# Loss function
y = tf.add(tf.pow(tf.subtract(1.0, x1_data), 2.0), 
           tf.multiply(100.0, tf.pow(tf.subtract(x2_data,tf.pow(x1_data, 2.0)), 2.0)), 'y')

#opt = tf.train.GradientDescentOptimizer(0.0035)
#train = opt.minimize(y)

opt = tf.train.GradientDescentOptimizer(1e-3)
grads_and_vars = opt.compute_gradients(y, [x1_data, x2_data])
clipped_grads_and_vars = [(tf.clip_by_value(g, -1., 1.), v) for g, v in grads_and_vars]
train = opt.apply_gradients(clipped_grads_and_vars)


sess = tf.Session()

init = tf.initialize_all_variables()
sess.run(init)

for step in range(20000):
    sess.run(train)
    if step % 100 == 0:
        print(step, sess.run(x1_data), sess.run(x2_data), sess.run(y))

0 [1.8902434] [0.75676066] [793.9243]
100 [1.7902387] [0.85675937] [552.0268]
200 [1.6902341] [0.9567581] [361.5271]
300 [1.5902294] [1.0567602] [217.04721]
400 [1.4902247] [1.1567649] [113.450935]
500 [1.39022] [1.2567695] [45.84207]
600 [1.2902154] [1.3567742] [9.563324]
700 [1.2009802] [1.4430666] [0.0404439]
800 [1.1951108] [1.4289846] [0.0381165]
900 [1.1893662] [1.4152687] [0.03590535]
1000 [1.1837461] [1.4019138] [0.03380606]
1100 [1.17825] [1.388914] [0.03181415]
1200 [1.1728771] [1.3762645] [0.0299254]
1300 [1.1676264] [1.3639578] [0.02813538]
1400 [1.1624974] [1.35199] [0.02644018]
1500 [1.1574893] [1.340355] [0.02483577]
1600 [1.1526014] [1.3290471] [0.02331822]
1700 [1.1478317] [1.3180588] [0.02188351]
1800 [1.1431798] [1.3073858] [0.02052809]
1900 [1.1386445] [1.2970217] [0.01924835]
2000 [1.1342242] [1.28696] [0.01804069]
2100 [1.1299179] [1.2771952] [0.01690177]
2200 [1.1257238] [1.2677207] [0.01582825]
2300 [1.1216404] [1.2585298] [0.01481687]
2400 [1.1176664] [1.249616

In [8]:
#       Tensorflow #1 Example
#   Tensorflow example of Gradient Descent
#   on a linear equation (y = mx + b)
#
#   https://github.com/FFY00/DeepLearning-Studies


import tensorflow as tf

m = tf.Variable([.3], dtype=tf.float32)
b = tf.Variable([-.3], dtype=tf.float32)
x = tf.placeholder(tf.float32)
linear_model = m * x + b # y = mx + b

y = tf.placeholder(tf.float32)
squared_deltas = tf.square(linear_model - y) # Also known as r^2
loss = tf.reduce_sum(squared_deltas)

# If you decrease the learning rate, you have to increase the loop range value
optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

x_set = [1, 2, 3, 4]
y_set = [0, -1, -2, -3]

for i in range(1000):
    sess.run(train, {x: x_set, y: y_set})

m_value, b_value, loss = sess.run([m, b, loss], {x: x_set, y: y_set})
print ( "y = {}x + {}".format(repr(m_value[0]), repr(b_value[0]))  )
print ("Loss: ", loss)


y = -0.9999969x + 0.9999908
Loss:  5.6999738e-11


In [115]:
import tensorflow as tf

# initialize arrays
x1_data = tf.Variable(initial_value=tf.random_uniform([1], -3, 3),name='x1')
x2_data = tf.Variable(initial_value=tf.random_uniform([1], -3, 3), name='x2')

# The Rosenbrock problem is defined as y = (1 - x1)^2 + 100 * (x2 - x1^2)^2, 
# giving the optimal solution on x1 = x2 = 1

# Loss function
#y = tf.add(tf.pow(tf.subtract(1.0, x1_data), 2.0), 
#           tf.multiply(100.0, tf.pow(tf.subtract(x2_data,tf.pow(x1_data, 2.0)), 2.0)), 'y')

y = (1.0-x1_data)**2 + 100.*(x2_data-x1_data**2)**2

print (y)

#opt = tf.train.GradientDescentOptimizer(0.0035)
#train = opt.minimize(y)

opt = tf.train.GradientDescentOptimizer(1e-3)
opt = tf.train.AdamOptimizer(1e-3)


grads_and_vars = opt.compute_gradients(y, [x1_data, x2_data])
clipped_grads_and_vars = [(tf.clip_by_value(g, -1., 1.), v) for g, v in grads_and_vars]
train = opt.apply_gradients(clipped_grads_and_vars)


sess = tf.Session()

init = tf.initialize_all_variables()
sess.run(init)

for step in range(20000):
    sess.run(train)
    if step % 100 == 0:
        print(step, sess.run(x1_data), sess.run(x2_data), sess.run(y))

Tensor("add_4:0", shape=(1,), dtype=float32)
0 [-1.3972076] [1.4620501] [29.77023]
100 [-1.297203] [1.5620548] [6.733525]
200 [-1.2421428] [1.5511112] [5.033916]
300 [-1.2004808] [1.4496552] [4.849343]
400 [-1.1575612] [1.3486443] [4.6626334]
500 [-1.1131102] [1.2479031] [4.4731355]
600 [-1.0668845] [1.1473306] [4.2802706]
700 [-1.0186123] [1.0468733] [4.08345]
800 [-0.96796685] [0.94649905] [3.881993]
900 [-0.914538] [0.84618735] [3.6750746]
1000 [-0.8577915] [0.74592423] [3.4616263]
1100 [-0.79700214] [0.6456998] [3.2402153]
1200 [-0.7311409] [0.54550666] [3.0088165]
1300 [-0.6586538] [0.4453393] [2.7643905]
1400 [-0.5769843] [0.34519356] [2.5019658]
1500 [-0.4813365] [0.245066] [2.2122633]
1600 [-0.36041316] [0.14495385] [1.873393]
1700 [-0.17624307] [0.04485497] [1.4025733]
1800 [0.02671082] [7.182778e-05] [0.94733304]
1900 [0.20114698] [0.03732746] [0.63914746]
2000 [0.35112444] [0.11945886] [0.42250603]
2100 [0.45071608] [0.19991261] [0.30275762]
2200 [0.5220393] [0.26977426] [0.

18800 [0.9999998] [0.9999998] [3.2294167e-12]
18900 [0.9999998] [0.9999998] [3.2294167e-12]
19000 [0.9999998] [0.9999998] [3.2294167e-12]
19100 [0.9999998] [0.9999998] [3.2294167e-12]
19200 [0.9999998] [0.9999998] [3.2294167e-12]
19300 [0.9999998] [0.9999998] [3.2294167e-12]
19400 [1.000078] [0.99989605] [6.7596447e-06]
19500 [0.99999285] [0.9999901] [2.0495603e-09]
19600 [0.99999845] [0.99999684] [2.756906e-12]
19700 [0.99999964] [0.999999] [9.009681e-12]
19800 [0.9999997] [0.99999934] [8.8817835e-14]
19900 [0.9999997] [0.99999934] [8.8817835e-14]


In [30]:
import tensorflow as tf

i = tf.constant(0)
c = lambda i: tf.less(i, 10)
b = lambda i: tf.add(i, 1)
r = tf.while_loop(c, b, [i])

with tf.Session() as sess:
   p = sess.run(r)
   print (p)


10


In [27]:
# Let mean vector and co-variance be:
mu = [1., 2] 
cov = [[ 1,  3/5],[ 3/5,  2]]

#Multivariate Normal distribution
gaussian = tf.contrib.distributions.MultivariateNormalFullCovariance(
           loc=mu,
           covariance_matrix=cov)

# Generate a mesh grid to plot the distributions
X, Y = tf.meshgrid(tf.range(-3, 3, 0.1), tf.range(-3, 3, 0.1))
idx = tf.concat([tf.reshape(X, [-1, 1]), tf.reshape(Y,[-1,1])], axis =1)
prob = tf.reshape(gaussian.prob(idx), tf.shape(X))

with tf.Session() as sess:
   p = sess.run(prob)
   m, c = sess.run([gaussian.mean(), gaussian.covariance()])
   print (m)
   print (c)
   # m is [1., 2.]
   # c is [[1, 0.6], [0.6, 2]]

[1. 2.]
[[1.  0.6]
 [0.6 2. ]]


In [108]:
import tensorflow as tf
import numpy as np
tfd = tf.contrib.distributions

x = tf.range(0, 1., 3,)

mvn = tfd.MultivariateNormalFullCovariance(
    loc=[0.0, 0.0, 0.0],
    covariance_matrix=[[0.1, 0.0, 0.0], 
                       [0.0, 0.1, 0.0], 
                       [0.0, 0.0, 0.1]]    )


with tf.Session() as sess:

   #p = sess.run(mvn.prob([0.31580481, 0.70949184, 0.19824165]))
   p = sess.run(mvn.prob([0.,         0.33333333, 0.66666667]))

   print (p)
    

0.1248408


In [133]:
import tensorflow as tf
import numpy as np
tfd = tf.contrib.distributions

N=10

x = np.linspace(0, 1, N, endpoint=False, dtype='float32')

Iden = np.identity(N)
I_cov = np.array(0.1*Iden, dtype='float32')
xx = x.reshape(-1,N)


mvn = tfd.MultivariateNormalFullCovariance(
    #loc=[0.0, 0.0, 0.0],
    covariance_matrix=I_cov   )


with tf.Session() as sess:

   #p = sess.run(mvn.prob([0.31580481, 0.70949184, 0.19824165]))
   p = sess.run(mvn.log_prob(x))

   print (p)
   print ( sess.run(mvn.mean()))
   print ( sess.run(mvn.stddev()))

-11.92646
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.31622776 0.31622776 0.31622776 0.31622776 0.31622776 0.31622776
 0.31622776 0.31622776 0.31622776 0.31622776]


In [135]:
import tensorflow as tf
import numpy as np
tfd = tf.contrib.distributions

#
# missing a factor somewhere, do not use this
#

N=10

x = np.linspace(0, 1, N, endpoint=False, dtype='float32')

#x = [[0.,         0.33333333, 0.66666667]]

mvn = tfd.MultivariateNormalDiag(
    loc=N*[0.0],
    scale_identity_multiplier=0.31622776    )


with tf.Session() as sess:

   #p = sess.run(mvn.prob([0.31580481, 0.70949184, 0.19824165]))
   p = sess.run(mvn.log_prob(x))
   print ( sess.run(mvn.mean()))
   print ( sess.run(mvn.stddev()))
   print (p)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.31622776 0.31622776 0.31622776 0.31622776 0.31622776 0.31622776
 0.31622776 0.31622776 0.31622776 0.31622776]
-11.92646


In [149]:
# Turn this into a helper function

import tensorflow as tf
import numpy as np
tfd = tf.contrib.distributions

def negMVN_diag(sig_dia,N,x): 
# N is the number of stocks
# x has the shape,time x stock
      Iden = np.identity(N)  #all the sigmas are the same, c-variances are zero
      I_cov = np.array(sig_dia*Iden, dtype='float32')
      x = x.reshape(-1,N)
      mvn = tfd.MultivariateNormalFullCovariance(
            covariance_matrix=I_cov   )


      with tf.Session() as sess:
         p = sess.run(-mvn.log_prob(x))

      return(p) # retur negative log value

N = 1000
x = np.linspace(0, 1, N, endpoint=False, dtype='float32')

print (negMVN_diag(0.1,N,x))

[1431.8148]


In [172]:
import tensorflow as tf

# initialize arrays
x1_data = tf.Variable(initial_value=tf.random_uniform([1], -3, 3),name='x1')
x2_data = tf.Variable(initial_value=tf.random_uniform([1], -3, 3), name='x2')

# The Rosenbrock problem is defined as y = (1 - x1)^2 + 100 * (x2 - x1^2)^2, 
# giving the optimal solution on x1 = x2 = 1

# Loss function
#y = tf.add(tf.pow(tf.subtract(1.0, x1_data), 2.0), 
#           tf.multiply(100.0, tf.pow(tf.subtract(x2_data,tf.pow(x1_data, 2.0)), 2.0)), 'y')

#y = (1.0-x1_data)**2 + 100.*(x2_data-x1_data**2)**2
y = (1.0-x1_data)**2 + x1_data 

print (y)

#opt = tf.train.GradientDescentOptimizer(0.0035)
#train = opt.minimize(y)

opt = tf.train.GradientDescentOptimizer(1e-3)
opt = tf.train.AdamOptimizer(1e-3)


grads_and_vars = opt.compute_gradients(y, [x1_data])
clipped_grads_and_vars = [(tf.clip_by_value(g, -1., 1.), v) for g, v in grads_and_vars]
train = opt.apply_gradients(clipped_grads_and_vars)


sess = tf.Session()

init = tf.initialize_all_variables()
sess.run(init)

for step in range(20000):
    sess.run(train)
    if step % 100 == 0:
        print(step, sess.run(x1_data), sess.run(x2_data), sess.run(y))

Tensor("add_7:0", shape=(1,), dtype=float32)
0 [-2.671099] [-1.4884] [10.805868]
100 [-2.5711062] [-1.4884] [10.181693]
200 [-2.4711134] [-1.4884] [9.577515]
300 [-2.3711207] [-1.4884] [8.993334]
400 [-2.271128] [-1.4884] [8.42915]
500 [-2.1711352] [-1.4884] [7.884963]
600 [-2.0711424] [-1.4884] [7.360773]
700 [-1.9711462] [-1.4884] [6.856563]
800 [-1.8711416] [-1.4884] [6.3723116]
900 [-1.7711369] [-1.4884] [5.9080625]
1000 [-1.6711322] [-1.4884] [5.4638147]
1100 [-1.5711275] [-1.4884] [5.039569]
1200 [-1.4711229] [-1.4884] [4.6353245]
1300 [-1.3711182] [-1.4884] [4.2510824]
1400 [-1.2711135] [-1.4884] [3.8868427]
1500 [-1.1711088] [-1.4884] [3.5426044]
1600 [-1.0711042] [-1.4884] [3.218368]
1700 [-0.9711012] [-1.4884] [2.914139]
1800 [-0.8711025] [-1.4884] [2.6299224]
1900 [-0.7711038] [-1.4884] [2.365705]
2000 [-0.6711051] [-1.4884] [2.1214871]
2100 [-0.5711064] [-1.4884] [1.897269]
2200 [-0.47110766] [-1.4884] [1.6930501]
2300 [-0.37110895] [-1.4884] [1.508831]
2400 [-0.27111024] [